[tool.flask-livetw]
flask_root = "/home/yu/Documents/WIG3007/smart_shopping_assistant"
static_folder = "static"
templates_folder = "templates"
templates_glob = "**/*.html"
base_layout = "layout.html"
livetw_folder = ".dev"
flask_app = "app"
